module.exports = {
  'block-closing-brace-newline-after': 'always',
  'block-closing-brace-newline-before': 'always',
  'block-no-empty': true,
  'block-opening-brace-newline-after': 'always',
  'color-hex-length': 'long',
  'color-named': 'never',
  'color-no-invalid-hex': true,
  'declaration-block-no-shorthand-property-overrides': true,
  'declaration-block-semicolon-newline-after': 'always',
  'declaration-block-trailing-semicolon': 'always',
  'declaration-colon-space-before': 'never',
  'declaration-colon-space-after': 'always',
  'declaration-no-important': true,
  indentation: 2,
  'max-nesting-depth': 3,
  'max-empty-lines': 1,
  'number-leading-zero': 'never',
  'number-no-trailing-zeros': true,
  'rule-empty-line-before': [
    'always',
    {
      except: ['first-nested'],
      ignore: ['after-comment'],
    },
  ],
  'scss/at-mixin-argumentless-call-parentheses': 'always',
  'selector-combinator-space-after': 'always',
  'selector-combinator-space-before': 'always',
  'selector-list-comma-newline-after': 'always',
  'selector-max-id': 0,
  'selector-type-case': 'lower',
  'string-quotes': 'single',
  'value-list-comma-space-after': 'always-single-line',
};
